{{- if eq (include "primehub-usage.enabled" .) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "primehub-usage.fullname" . }}-db
type: Opaque
data:
  username: {{.Values.usage.dbUser | b64enc | quote }}
  password: {{.Values.usage.dbPassword | b64enc | quote }}
{{- end }}
